//#region Reset doable for this state

// GET FAVORITE_ TYPE
export const GET_FAVORITE_REQUEST = "GET_FAVORITE_REQUEST";
export const GET_FAVORITE_SUCCESS = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_FAILURE = "GET_FAVORITE_FAILURE";

// ADD FAVORITE_ TYPE
export const ADD_FAVORITE_REQUEST = "ADD_FAVORITE_REQUEST";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAILURE = "ADD_FAVORITE_FAILURE";

// CREATE FAVORITE_ TYPE
export const EDIT_FAVORITE_REQUEST = "EDIT_FAVORITE_REQUEST";
export const EDIT_FAVORITE_SUCCESS = "EDIT_FAVORITE_SUCCESS";
export const EDIT_FAVORITE_FAILURE = "EDIT_FAVORITE_FAILURE";

// DEL FAVORITE_ TYPE
export const DEL_FAVORITE_REQUEST = "DEL_FAVORITE_REQUEST";
export const DEL_FAVORITE_SUCCESS = "DEL_FAVORITE_SUCCESS";
export const DEL_FAVORITE_FAILURE = "DEL_FAVORITE_FAILURE";

//#endregion

/* new-constant-export-goes-here */
